### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by SilenceDev** [G-mel/Who-Is-At-The-Door#1]
I got everything pretty much working, but once I ran node firebase.js I get the syntaxError

firebase.js:27
    Raspistill.on('close', (code) => {
                                                     ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by G-mel** [comment]
Are you running firebase.js on the raspberry pi or on your personal computer? If you are debugging on your personal computer, then you must comment out lines 26,27 and 62 to avoid the Raspistill syntax error. This is because you are calling the raspistill command keyword that is for the raspberry pi camera module and are waiting for that command to execute (e.g. take a picture from the raspberry pi camera) before continuing on to the facial recognition lines of code. Hope this helps.

Himel

**Comment by SilenceDev** [comment]
Thanks got it working!
